@startuml
class util.GameSetup {
+ {static} Board createStandardBoard()
- {static} void setupPieces(Board,Color,int)
}

class ui.ChessApp {
- {static} int BOARD_SIZE
- double TILE
- {static} Color LIGHT
- {static} Color DARK
- {static} Color SELECT
- {static} Color MOVE_HIGHLIGHT
- {static} Color SHOOT_HIGHLIGHT
- Map<String,Image> pieceImages
- AudioClip captureSound
- AudioClip moveSound
- AudioClip gameOverSound
- Button newGameButton
- Button resignButton
- GameEngine engine
- Canvas canvas
- Label statusLabel
- Position selectedPosition
- List<Position> legalMoves
- List<Position> shootTargets
+ void start(Stage)
- void resizeBoard(Scene)
- Label createStatusLabel()
- void loadImages()
- void loadSounds()
- void draw()
- void drawTile(GraphicsContext,int,int,double,double)
- void drawHighlights(GraphicsContext,Board,Position,double,double)
- void drawCoordinates(GraphicsContext,int,int,double,double)
- void drawPiece(GraphicsContext,Piece,double,double)
- void drawFallbackPiece(GraphicsContext,Piece,double,double)
- void drawPromotionOverlay(GraphicsContext)
- void handleClick(int,int)
- void handlePromotionClick(int,int)
- void resetGame()
- void resign()
- void selectPiece(Position,Piece)
- void clearSelection()
- void updateStatus(MoveResult)
- List<Position> getStabTargets(Piece)
- List<Position> getShootTargets(Piece)
- MoveResult makeMove(Position,Position)
+ {static} void main(String[])
}


class main.Main {
+ {static} void main(String[])
}



javafx.application.Application <|-- ui.ChessApp
@enduml