@startuml
class util.GameSetupTest {
~ void whiteTest()
~ void blackTest()
~ void allWhitePiecesAreCorrectColor()
~ void allBlackPiecesAreCorrectColor()
}

class core.PositionTest {
~ void validPositionsAreAccepted()
~ void outOfBoundsAreInvalid()
~ void offsetWorks()
~ void equalityIsValueBased()
~ void toStringIsChessNotation()
}

class pieces.MageTest {
- Board board
~ void setUp()
~ void moveTest()
~ void shootTest()
~ void shootExceedTest()
~ void shotBlockedByAllyPiece()
~ void testShootWarrior()
~ void pieceRemovedFromBoardTest()
}


class pieces.AssassinTest {
- Board board
~ void setUp()
~ void moveTest()
~ void jumpTest()
~ void landingTest()
~ void captureTest()
}


class pieces.ArcherTest {
- Board board
~ void setUp()
~ void moveTest()
~ void shootTest()
~ void shootExceedTest()
~ void shotBlockedTest()
~ void shootAllyTest()
~ void testShootWarrior()
~ void pieceRemovedFromBoardTest()
}


class core.GameEngineTest {
- Board board
- GameEngine engine
~ void setUp()
~ void whiteFirstTest()
~ void alternatingTurnTest()
~ void opponentPieceTest()
~ void returnedCapturedPieceTest()
~ void gameEndTest()
~ void totalMovesTest()
~ void mageShootTest()
~ void archmageShootTest()
~ void archerShootTest()
~ void whitePromotionTest()
~ void blackPromotionTest()
}


class pieces.ArchmageTest {
- Board board
~ void setUp()
~ void moveTest()
~ void shootTest()
~ void shotBlockedTest()
~ void cooldownTest()
~ void cooldownCountTest()
~ void downtimeTest()
~ void testShootWarrior()
~ void pieceRemovedFromBoardTest()
}


class pieces.WarriorTest {
- Board board
~ void setUp()
~ void startsWithTwoLives()
~ void survivesFirstHit()
~ void diesOnSecondHit()
~ void movesForwardOneSquare()
~ void movesTwoSquaresOnFirstMove()
~ void cannotMoveTwoSquaresAfterFirstMove()
~ void capturesDiagonally()
~ void cannotCaptureForward()
~ void blackWarriorMovesDown()
}


class pieces.DragonTest {
- Board board
~ void setUp()
~ void moveTest()
~ void blockedTest()
~ void captureTest()
}


@enduml